### ISSUE TITLE
報到處

### ISSUE THREAD

**Issue by noracami** [we-have-TTA/no-idea#1]
請簽名報到 🔮

**Comment by zxcvbnm7548** [comment]
我來了

**Comment by chutienyuan** [comment]
hiiiiii

**Comment by Yojijun** [comment]
hi~~~~~~~~~~~~~

**Comment by oSeanChen** [comment]
hihi

**Comment by RexXKao** [comment]
hi

**Comment by noracami** [comment]
要到信箱確認喔 @oSeanChen @zxcvbnm7548 @RexXKao

**Comment by RexXKao** [comment]
> 要到信箱確認喔 @oSeanChen @zxcvbnm7548 @RexXKao

已確認

**Comment by noracami** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [item1](https://trello.com/c/vT8RsaUp/1-item1)

**Comment by noracami** [comment]
徵求一位志願者試試 close issue 😋

**Comment by oSeanChen** [comment]
> 徵求一位志願者試試 close issue 😋

怎麼close?

**Comment by noracami** [comment]
> > 徵求一位志願者試試 close issue 😋
> 
> 怎麼close?

在 Comment 左邊 有 Close 可以按嗎
看不到的話再調權限 🤣

**Comment by oSeanChen** [comment]
有吧 我close掉了

**Comment by oSeanChen** [comment]
有吧我close了
